services:
  - type: web
    name: hajj-omra-booking-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5001

  - type: static
    name: hajj-omra-booking-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://hajj-omra-booking-api.onrender.com 