services:
  - type: web
    name: hajj-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: "https://hajj-omra-booking-backend.onrender.com" 